### ISSUE TITLE
Add a verbose/debug option for the client mode

### ISSUE THREAD

**Issue by cpeintre** [joshuaprunier/trite#8]
When there is an error during the process, for example a syntax error, it could be tricky to find which table script is involved.

**Comment by joshuaprunier** [comment]
Errors are most likely encountered during the table apply phase. This now has error handling for each step in that process. If an error occurs an ERROR status is displayed for the table to stdout, an error message is logged to an error file. The default error file is trite.err in the current working directory where trite is run but can be specified using the -errorLog flag. When an error occurs a copy of the mysql processlist and innodb status are also captured and logged to the error file to aid in debugging. 

Some cleanup is also performed depending on the apply step that failed. The xtrabackup files trite downloaded will be removed if a table can not be dropped, created or its tablespace discarded. The table will also be dropped if importing of the tablespace fails.

Commits related to error handling/logging: 67a5a273806a0791071fbbaa6c415361b338c9cc, 11b11fadfa5d8dad91d089ad0806e2a7ba92ae5d, 12c181ade0b2e4e88824bad584e78ca54e1d1a30, 9e0e1b145be3ba698c608cebede62f764ed9fea5, 3e89a6d8e9a3d63556b452ad51ca59fb796422a3
